// AUTO-GENERATED by scripts/generate-routes.mjs — safe to regenerate.
// To change the copy/logic these pages render, edit components/CityHub.tsx
// or lib/local-service-content.ts instead of this file.
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { buildMetadata } from "@/lib/seo";
import { localServiceIntro, localServiceFaqExtra, localServiceMeta } from "@/lib/local-service-content";
import LocalServicePage from "@/components/LocalServicePage";
import { getCityBySlug } from "@/data/cities";
import { getServiceBySlug } from "@/data/services";

const SERVICE_SLUG = "osuszanie-po-zalaniu";
const CITY_SLUG = "gdansk";
const service = getServiceBySlug(SERVICE_SLUG)!;
const city = getCityBySlug(CITY_SLUG);

export const metadata: Metadata = city
  ? buildMetadata({
      ...localServiceMeta(SERVICE_SLUG, service.name, city),
      path: `/${SERVICE_SLUG}-${CITY_SLUG}`,
    })
  : {};

export default function Page() {
  if (!city) {
    notFound();
    return null;
  }
  return (
    <LocalServicePage
      service={service}
      city={city}
      intro={localServiceIntro(SERVICE_SLUG, city)}
      faqExtra={localServiceFaqExtra(SERVICE_SLUG, city)}
    />
  );
}
