// AUTO-GENERATED by scripts/generate-routes.mjs — safe to regenerate.
// To change the copy/logic these pages render, edit components/CityHub.tsx
// or lib/local-service-content.ts instead of this file.
import type { Metadata } from "next";
import CityHubPage, { cityHubMetadata } from "@/components/CityHub";

export const metadata: Metadata = cityHubMetadata("reda");

export default function Page() {
  return <CityHubPage citySlug="reda" />;
}
