#!/usr/bin/env node
/**
 * scripts/generate-routes.mjs
 * ============================================================================
 * Regenerates the literal route wrapper files for:
 *   - City hub pages:        app/hydraulik-{city}/page.tsx           (one per city in data/cities.ts)
 *   - Service × city pages:  app/{service}-{city}/page.tsx           (one per entry in city.localServicePages)
 *
 * WHY LITERAL FOLDERS INSTEAD OF A DYNAMIC [city] SEGMENT:
 * Next.js App Router dynamic segments must wrap the ENTIRE folder name in
 * brackets ([city]), not a partial segment like "hydraulik-[city]". That
 * pattern is not the documented convention and its behavior is not something
 * this project relies on. Every route below is therefore a real, literal
 * folder — guaranteed valid, and provably 1:1 with data/cities.ts and
 * data/services.ts (see the reconciliation this script performs).
 *
 * SAFETY GUARANTEES (read before running):
 *   1. NEVER deletes anything. Not a file, not a folder — ever. If a city is
 *      removed from data/cities.ts, its old route folder is left untouched;
 *      the script only reports it as "orphaned" so a human can decide.
 *   2. NEVER overwrites a file it doesn't own. Every file this script writes
 *      starts with the AUTO-GENERATED marker comment below. On re-run, a
 *      target file is only overwritten if that marker is present (i.e. it
 *      was produced by this script and is safe to regenerate). Any file
 *      without the marker — meaning a human hand-edited it, or it's an
 *      unrelated file that happens to share a path — is left alone and
 *      reported as SKIPPED.
 *   3. Deterministic: given the same data/cities.ts and data/services.ts,
 *      output is byte-identical every time. No timestamps, no randomness.
 *   4. Dry-run by default. Nothing is written to disk unless you pass --write.
 *
 * USAGE:
 *   node scripts/generate-routes.mjs            # dry run — prints a plan
 *   node scripts/generate-routes.mjs --write     # actually writes files
 *
 * This script parses data/cities.ts and data/services.ts as TEXT (regex),
 * not as executed TypeScript — so it has no dependency on node_modules and
 * runs with plain Node.js.
 * ============================================================================
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WRITE = process.argv.includes("--write");

const MARKER =
  "// AUTO-GENERATED by scripts/generate-routes.mjs — safe to regenerate.\n" +
  "// To change the copy/logic these pages render, edit components/CityHub.tsx\n" +
  "// or lib/local-service-content.ts instead of this file.\n";

function readData(relPath) {
  return readFileSync(path.join(ROOT, relPath), "utf8");
}

function parseCitySlugs(citiesTs) {
  const slugs = [];
  const re = /\{\s*\n\s*slug: "([a-z0-9-]+)"/g;
  let m;
  while ((m = re.exec(citiesTs))) slugs.push(m[1]);
  return slugs;
}

function parseCityLocalServicePages(citiesTs) {
  const map = {};
  const blockRe = /\{\s*\n\s*slug: "([a-z0-9-]+)"[\s\S]*?localServicePages: \[([^\]]*)\]/g;
  let m;
  while ((m = blockRe.exec(citiesTs))) {
    const [, slug, rawList] = m;
    const services = [...rawList.matchAll(/"([a-z0-9-]+)"/g)].map((x) => x[1]);
    map[slug] = services;
  }
  return map;
}

function parseServiceSlugs(servicesTs) {
  const slugs = [];
  const re = /\{\s*\n\s*slug: "([a-z0-9-]+)"/g;
  let m;
  while ((m = re.exec(servicesTs))) slugs.push(m[1]);
  return slugs;
}

// --- Templates (must match components/CityHub.tsx and the combo-page shape) ---

function hubTemplate(citySlug) {
  return (
    MARKER +
    `import type { Metadata } from "next";\n` +
    `import CityHubPage, { cityHubMetadata } from "@/components/CityHub";\n\n` +
    `export const metadata: Metadata = cityHubMetadata("${citySlug}");\n\n` +
    `export default function Page() {\n` +
    `  return <CityHubPage citySlug="${citySlug}" />;\n` +
    `}\n`
  );
}

function comboTemplate(serviceSlug, citySlug) {
  return (
    MARKER +
    `import type { Metadata } from "next";\n` +
    `import { notFound } from "next/navigation";\n` +
    `import { buildMetadata } from "@/lib/seo";\n` +
    `import { localServiceIntro, localServiceFaqExtra, localServiceMeta } from "@/lib/local-service-content";\n` +
    `import LocalServicePage from "@/components/LocalServicePage";\n` +
    `import { getCityBySlug } from "@/data/cities";\n` +
    `import { getServiceBySlug } from "@/data/services";\n\n` +
    `const SERVICE_SLUG = "${serviceSlug}";\n` +
    `const CITY_SLUG = "${citySlug}";\n` +
    `const service = getServiceBySlug(SERVICE_SLUG)!;\n` +
    `const city = getCityBySlug(CITY_SLUG);\n\n` +
    `export const metadata: Metadata = city\n` +
    `  ? buildMetadata({\n` +
    `      ...localServiceMeta(SERVICE_SLUG, service.name, city),\n` +
    "      path: `/${SERVICE_SLUG}-${CITY_SLUG}`,\n" +
    `    })\n` +
    `  : {};\n\n` +
    `export default function Page() {\n` +
    `  if (!city) {\n` +
    `    notFound();\n` +
    `    return null;\n` +
    `  }\n` +
    `  return (\n` +
    `    <LocalServicePage\n` +
    `      service={service}\n` +
    `      city={city}\n` +
    `      intro={localServiceIntro(SERVICE_SLUG, city)}\n` +
    `      faqExtra={localServiceFaqExtra(SERVICE_SLUG, city)}\n` +
    `    />\n` +
    `  );\n` +
    `}\n`
  );
}

// --- Plan ---

const citiesTs = readData("data/cities.ts");
const servicesTs = readData("data/services.ts");

const citySlugs = parseCitySlugs(citiesTs);
const localServicePages = parseCityLocalServicePages(citiesTs);
const serviceSlugs = new Set(parseServiceSlugs(servicesTs));

const plan = [];
for (const citySlug of citySlugs) {
  plan.push({ dir: `app/hydraulik-${citySlug}`, content: hubTemplate(citySlug) });
}
for (const [citySlug, services] of Object.entries(localServicePages)) {
  for (const serviceSlug of services) {
    if (!serviceSlugs.has(serviceSlug)) {
      console.warn(
        `⚠️  ${citySlug} lists localServicePages entry "${serviceSlug}" which is not a known service slug — skipping.`
      );
      continue;
    }
    plan.push({ dir: `app/${serviceSlug}-${citySlug}`, content: comboTemplate(serviceSlug, citySlug) });
  }
}

// --- Execute (or report) ---

let created = 0,
  upToDate = 0,
  wouldUpdate = 0,
  skippedForeign = 0;

for (const { dir, content } of plan) {
  const filePath = path.join(ROOT, dir, "page.tsx");
  const exists = existsSync(filePath);

  if (!exists) {
    console.log(`${WRITE ? "CREATE" : "[dry-run] would CREATE"}: ${dir}/page.tsx`);
    if (WRITE) {
      mkdirSync(path.join(ROOT, dir), { recursive: true });
      writeFileSync(filePath, content, "utf8");
    }
    created++;
    continue;
  }

  const current = readFileSync(filePath, "utf8");
  const ownedByScript = current.startsWith("// AUTO-GENERATED by scripts/generate-routes.mjs");

  if (!ownedByScript) {
    console.log(`SKIP (hand-edited, not owned by this script): ${dir}/page.tsx`);
    skippedForeign++;
    continue;
  }

  if (current === content) {
    upToDate++;
    continue;
  }

  console.log(`${WRITE ? "UPDATE" : "[dry-run] would UPDATE"}: ${dir}/page.tsx (content drifted from template)`);
  if (WRITE) writeFileSync(filePath, content, "utf8");
  wouldUpdate++;
}

console.log("\n--- Summary ---");
console.log(`Planned routes: ${plan.length}`);
console.log(`${WRITE ? "Created" : "Would create"}: ${created}`);
console.log(`${WRITE ? "Updated" : "Would update"}: ${wouldUpdate}`);
console.log(`Already up to date: ${upToDate}`);
console.log(`Skipped (hand-edited / not script-owned): ${skippedForeign}`);
if (!WRITE) console.log("\nThis was a DRY RUN. Re-run with --write to apply changes.");
console.log("\nNo files or folders were deleted by this script (it never deletes).");
